Update README.md
martinmags/july-challenge-tbd pull request #1
Opened 2021-07-01 18:17 UTC by martinmags

2021-07-01 22:02 UTC, alexalewis approved these changes, later dismissed

2021-07-01 22:39 UTC, nicolegooden commented on README.md
> +A web app that acts as a directory in finding employees in their areas of expertise and team involvment.
@martinmags 
I think the sentence is read a little more easily this way:
A web app that acts as a directory to find employees based on their areas of expertise and team involvement.

2021-07-01 22:41 UTC, nicolegooden requested changes
I think rephrasing the one-liner (project description) could be a good idea, otherwise this looks good! Thanks for taking on the very first PR.

2021-07-07 19:59 UTC, nicolegooden approved these changes
Looks good!

2021-07-07 19:59 UTC, merged